obj-$(CONFIG_NANDROID_BINDER_IPC)	+= binder.o
obj-$(CONFIG_NANDROID_LOGGER)		+= logger.o
obj-$(CONFIG_NANDROID_RAM_CONSOLE)	+= ram_console.o
obj-$(CONFIG_NANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_NANDROID_TIMED_GPIO)	+= timed_gpio.o
obj-$(CONFIG_NANDROID_LOW_MEMORY_KILLER)	+= lowmemorykiller.o
