/*
 *  DO NOT MODIFY THIS FILE
 *  This file is generated by this package's build script (package.bld).
 */
/*!
 *  ======== Version ========
 *  Version for the ti.mas.vpe package
 */
metaonly module Version inherits ti.mas.swtools.IVersion {

    /*!
     *  ======== VERSION ========
     *  Major version number of ti.mas.vpe
     */
    override const UInt16 MAJOR = 3;

    /*!
     *  ======== REVISION ========
     *  Minor version number of ti.mas.vpe
     */
    override const UInt16 MINOR = 2;

    /*!
     *  ======== XVERTICAL ========
     *  Xvertical number of ti.mas.vpe
     */
    const UInt16 XVERTICAL = 0;

    /*!
     *  ======== PATCH ========
     *  Patch level of ti.mas.vpe
     */
    override const UInt16 PATCH = 1;

    /*
     *  ======== WIDTH ========
     *  Minimum print width for ti.mas.vpe
     */
    override const UInt16 WIDTH = 4;
    
    /*
     *  ======== PACKAGING STD COMPLIANCE ========
     *  Packaging Standard Compliance field
     */
    const UInt16 PKGSTD = 1;        

}
