/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT i2c_test.cdb */

/*  Include Header File  */
#include "i2c_testcfg.h"

/*  Config Structures */
/*  Handles  */
